import '@/app/globals.css'
import Footer from '@/components/Footer'
import SearchHeader from '@/components/SearchHeader'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const searchLayout = ({children}) => {
  return (
    <div>
        <SearchHeader />
        {children}
        <Footer />
    </div>
  )
}

export default searchLayout